- name: "Create directory"
  ansible.builtin.file:
    path: "{{ monitor.dir }}"
    state: directory
    mode: "0755"
  become: true

- name: Create sub directories
  ansible.builtin.file:
    path: "{{ monitor.dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "grafana"
    - "mimir"
    - "nginx"
    - "prometheus"
    - "loki"
    - "minio"

- name: "Copy tunnel files"
  ansible.builtin.import_role:
    name: "tunnel"
    tasks_from: "main.yml"
  vars:
    tunnel_dst: "{{ monitor.dir }}"

- name: "Set monitor compose.yml"
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ monitor.dir }}/compose.yml"
    mode: "0644"
  notify: "Restart_monitor"

- name: "Template config files"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ monitor.dir }}/{{ item | regex_search('(grafana|mimir|nginx|prometheus)') }}/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "0644"
  with_fileglob:
    - "templates/grafana/*.j2"
    - "templates/mimir/*.j2"
    - "templates/nginx/*.j2"
    - "templates/prometheus/*.j2"
  notify: "Restart_monitor"

- name: "Config files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ monitor.dir }}/{{ item | regex_search('(grafana|mimir|nginx|prometheus)') }}/{{ item | basename }}"
    mode: "0644"
  with_fileglob:
    - "grafana/*"
  notify: "Restart_monitor"

- name: "Docker run monitor"
  community.docker.docker_compose_v2:
    project_src: "{{ monitor.dir }}"
    state: "present"

- name: "Set Caddyfile"
  ansible.builtin.template:
    src: "Caddyfile.j2"
    dest: "{{ caddy_dir }}/vhosts/monitor"
    mode: "0644"
  become: true
  notify: Restart_caddy
