- name: "Add gpg key"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    force: true
  become: true

- name: "Add apt repository"
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: true
  become: true

- name: "Install docker"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: "Docker login"
  community.docker.docker_login:
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
    registry_url: "{{ docker.registry }}"
