- name: "Set key for observer"
  ansible.posix.authorized_key:
    user: isucon
    key: "{{ lookup('file', 'id_ed25519.pub') }}"

- name: "Install observer"
  ansible.builtin.include_role:
    name: prometheus.prometheus.systemd_exporter
  vars:
    systemd_exporter_log_level: error
    systemd_exporter_version: "0.5.0"
