- name: "Update and upgrade"
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
# - name: Add gpg keys
#   ansible.builtin.get_url:
#     url: "{{ item.url }}"
#     dest: "{{ item.dest }}"
#     mode: "0644"
#     force: true
#   become: true
#   loop:
#     - url: https://apt.grafana.com/gpg.key
#       dest: /etc/apt/keyrings/grafana.asc

# - name: Add apt repositories
#   ansible.builtin.apt_repository:
#     repo: deb [arch=amd64 signed-by="{{ item.key }}"] "{{ item.repository }}" stable main
#     state: present
#     update_cache: true
#   become: true
#   loop:
#     - key: /etc/apt/keyrings/grafana.asc
#       repository: https://apt.grafana.com

# - name: "Install tools"
#   become: true
#   ansible.builtin.apt:
#     name:
#       - git
#       - unzip
#       - dstat
#       - tree
#       - make
#       - alloy
