- name: "Create directory"
  ansible.builtin.file:
    path: "/srv/pprotein"
    state: directory
    mode: "0755"
  become: true

- name: "Copy tunnel files"
  ansible.builtin.import_role:
    name: "tunnel"
    tasks_from: "main.yml"
  vars:
    tunnel_dst: "/srv/pprotein"

- name: "Set pprotein compose.yml"
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "/srv/pprotein/compose.yml"
    mode: "0644"
  notify: "Restart_pprotein"

- name: "Docker run pprotein"
  community.docker.docker_compose_v2:
    project_src: "{{ pprotein.dir }}"
    state: "present"

- name: "Set Caddyfile"
  ansible.builtin.template:
    src: "Caddyfile.j2"
    dest: "{{ caddy_dir }}/vhosts/pprotein"
    mode: "0644"
  become: true
  notify: Restart_caddy
